// Generated by gencpp from file pca9685_board/Servo.msg
// DO NOT EDIT!


#ifndef PCA9685_BOARD_MESSAGE_SERVO_H
#define PCA9685_BOARD_MESSAGE_SERVO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pca9685_board
{
template <class ContainerAllocator>
struct Servo_
{
  typedef Servo_<ContainerAllocator> Type;

  Servo_()
    : name()
    , value(0.0)  {
    }
  Servo_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef float _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::pca9685_board::Servo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pca9685_board::Servo_<ContainerAllocator> const> ConstPtr;

}; // struct Servo_

typedef ::pca9685_board::Servo_<std::allocator<void> > Servo;

typedef boost::shared_ptr< ::pca9685_board::Servo > ServoPtr;
typedef boost::shared_ptr< ::pca9685_board::Servo const> ServoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pca9685_board::Servo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pca9685_board::Servo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pca9685_board::Servo_<ContainerAllocator1> & lhs, const ::pca9685_board::Servo_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pca9685_board::Servo_<ContainerAllocator1> & lhs, const ::pca9685_board::Servo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pca9685_board

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pca9685_board::Servo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pca9685_board::Servo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pca9685_board::Servo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pca9685_board::Servo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pca9685_board::Servo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pca9685_board::Servo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pca9685_board::Servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db3486341a840969e8845548decf6f11";
  }

  static const char* value(const ::pca9685_board::Servo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb3486341a840969ULL;
  static const uint64_t static_value2 = 0xe8845548decf6f11ULL;
};

template<class ContainerAllocator>
struct DataType< ::pca9685_board::Servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pca9685_board/Servo";
  }

  static const char* value(const ::pca9685_board::Servo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pca9685_board::Servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# the Servo message is commonly used message in this package to\n"
"# assign a value to a specific servo. the purpose of the value is\n"
"# dependent on the topic or service being called\n"
"\n"
"string name\n"
"float32 value\n"
;
  }

  static const char* value(const ::pca9685_board::Servo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pca9685_board::Servo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Servo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pca9685_board::Servo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pca9685_board::Servo_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PCA9685_BOARD_MESSAGE_SERVO_H
